"""baseline — 2026-09-01 시점 스키마

Revision ID: 0001
Revises: 
Create Date: 2026-09-01 14:59:54.432213
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


def _pgvector_ready() -> bool:
    """확장이 실제로 설치돼 있는지. 없으면 임베딩 테이블을 건너뛴다."""
    bind = op.get_bind()
    return bool(bind.execute(sa.text("SELECT 1 FROM pg_extension WHERE extname='vector'")).scalar())
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('applied', 'interview', 'accepted', 'rejected')", name='ck_email_templates_stage'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('interviewer_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_at < end_at', name='ck_interviewer_availability_range'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interviewer_availability_user_start', 'interviewer_availability', ['interviewer_id', 'start_at'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'open', 'closed')", name='ck_job_postings_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_token')
    )
    op.create_table('applications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_posting_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('career_years', sa.SmallInteger(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('self_intro', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_summary_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_summary_model', sa.String(length=200), nullable=True),
    sa.Column('current_stage', sa.String(length=20), server_default=sa.text("'applied'"), nullable=False),
    sa.Column('privacy_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), server_default=sa.text("'form'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_stage IN ('applied', 'screening', 'interview', 'accepted', 'rejected')", name='ck_applications_stage'),
    sa.CheckConstraint("source IN ('form', 'manual')", name='ck_applications_source'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'email', name='uq_applications_posting_email')
    )
    op.create_index('ix_applications_created_id', 'applications', [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_applications_posting_stage', 'applications', ['job_posting_id', 'current_stage'], unique=False)
    op.create_table('application_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_application_notes_app_created', 'application_notes', ['application_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('actor_kind', sa.String(length=10), server_default=sa.text("'system'"), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_kind IN ('human', 'agent', 'system')", name='ck_email_logs_actor_kind'),
    sa.CheckConstraint("stage IN ('applied', 'screening', 'interview', 'accepted', 'rejected', 'custom')", name='ck_email_logs_stage'),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed')", name='ck_email_logs_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluator_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score BETWEEN 1 AND 5', name='ck_evaluations_score'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('resume', 'cover_letter')", name='ck_files_kind'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewer_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'interviewer_id', name='uq_interviewer_assignments')
    )
    op.create_table('schedule_proposals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'proposed'"), nullable=False),
    sa.Column('confirmed_slot_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'confirmed', 'expired', 'canceled')", name='ck_schedule_proposals_status'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['confirmed_slot_id'], ['schedule_slots.id'], name='fk_schedule_proposals_confirmed_slot', use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_schedule_proposals_app_created', 'schedule_proposals', ['application_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('stage_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('application_id', sa.BigInteger(), nullable=False),
    sa.Column('from_stage', sa.String(length=20), nullable=True),
    sa.Column('to_stage', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("to_stage IN ('applied', 'screening', 'interview', 'accepted', 'rejected')", name='ck_stage_history_to_stage'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_slots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('proposal_id', sa.BigInteger(), nullable=False),
    sa.Column('interviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('start_at < end_at', name='ck_schedule_slots_range'),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['schedule_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id', 'interviewer_id', 'start_at', name='uq_schedule_slots')
    )

    # 순환 FK — schedule_proposals.confirmed_slot_id ↔ schedule_slots.proposal_id.
    # 모델이 use_alter=True 로 선언해 **두 테이블이 다 생긴 뒤** 따로 건다.
    # autogenerate 는 이걸 빠뜨린다(alembic check 로 발견).
    op.create_foreign_key(
        "fk_schedule_proposals_confirmed_slot",
        "schedule_proposals",
        "schedule_slots",
        ["confirmed_slot_id"],
        ["id"],
    )

    # ── application_embeddings (ADR-0021) ────────────────────────────
    # **조건부다.** pgvector 확장이 없는 DB 에서 vector 타입을 만들려 들면 실패하고,
    # alembic 은 한 트랜잭션이라 위에서 만든 테이블까지 통째로 롤백된다.
    # main.py lifespan · conftest 가 이미 같은 판단을 한다.
    if _pgvector_ready():
        op.create_table(
            "application_embeddings",
            sa.Column("id", sa.BigInteger(), nullable=False),
            sa.Column("application_id", sa.BigInteger(), nullable=False),
            sa.Column("embedding", Vector(768), nullable=False),
            sa.Column("model_name", sa.String(length=100), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.ForeignKeyConstraint(["application_id"], ["applications.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("application_id"),
        )
        # <=> 가 전건 스캔이 되지 않게 (ADR-0021)
        op.create_index(
            "ix_application_embeddings_hnsw",
            "application_embeddings",
            ["embedding"],
            postgresql_using="hnsw",
            postgresql_ops={"embedding": "vector_cosine_ops"},
        )
    else:
        print("pgvector 확장이 없어 application_embeddings 를 건너뛴다 — 시맨틱 검색만 꺼진다")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_schedule_proposals_confirmed_slot", "schedule_proposals", type_="foreignkey")
    if _pgvector_ready():
        op.drop_index("ix_application_embeddings_hnsw", table_name="application_embeddings")
        op.drop_table("application_embeddings")
    op.drop_table('schedule_slots')
    op.drop_table('stage_history')
    op.drop_index('ix_schedule_proposals_app_created', table_name='schedule_proposals')
    op.drop_table('schedule_proposals')
    op.drop_table('interviewer_assignments')
    op.drop_table('files')
    op.drop_table('evaluations')
    op.drop_table('email_logs')
    op.drop_index('ix_application_notes_app_created', table_name='application_notes')
    op.drop_table('application_notes')
    op.drop_index('ix_applications_posting_stage', table_name='applications')
    op.drop_index('ix_applications_created_id', table_name='applications')
    op.drop_table('applications')
    op.drop_table('job_postings')
    op.drop_index('ix_interviewer_availability_user_start', table_name='interviewer_availability')
    op.drop_table('interviewer_availability')
    op.drop_table('email_templates')
    op.drop_table('users')
    # ### end Alembic commands ###
